[template]
prefix = "/odyssey"

src = "odyssey.tmpl"
dest = "/opt/odyssey.conf"

#owner = "nginx"
#mode = "0644"

keys = [
  "/"
#  "/upstream",
]

#check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
#reload_cmd = "/usr/sbin/service nginx reload"
