version: "3.4"

services:
  postgres:
    image: chernoskutov/postgres-pro:9.6
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '6543:5432'

  odyssey:
    build: 
      context: .
    environment:
      ODYSSEY_MAXCLIENTS: 2048
      ODYSSEY_POSTGRES_HOST: postgres
      ODYSSEY_POSTGRES_PORT: 5432
      ODYSSEY_POSTGRES_POOL_MODE: transaction
      ODYSSEY_POSTGRES_POOL_SIZE: 5
      ODYSSEY_POSTGRES_POOL_TIMEOUT: 500
      ODYSSEY_POSTGRES_POOL_TTL: 15

      # echo "md5$(echo -n "PASSWORDusername" | md5)"
      ODYSSEY_POSTGRES_AUTH_MECHANISM: md5
      ODYSSEY_POSTGRES_USERNAME: username
      ODYSSEY_POSTGRES_PASSWORD: md549c0c19260f12fcb287f6722c4737335
    ports:
      - '5432:5432'
